"""Baseline single-prompt architecture.

The baseline is deliberately simple: a single LLM call, guided by a strong
system prompt that bundles the essential guidance from all four specialists
into one message. Its role in the study is to answer the question "does the
overhead of multi-agent orchestration actually beat a well-crafted
single-prompt approach?" That question is only meaningful if the baseline
prompt itself is strong; a straw-man baseline would make every multi-agent
condition look artificially good.

The interaction is logged with:

* ``architecture = "baseline_single_prompt"``
* ``agent = "baseline"``
* ``phase = "initial"``

so downstream analysis can compare aggregate cost and latency against the
multi-agent conditions in like-for-like terms.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from agents.base import Agent, RunContext
from config import prompts
from config.settings import Settings
from utils.llm_client import LLMClient
from utils.logging import ExperimentLogger

#: Canonical architecture name used in interaction log lines.
ARCHITECTURE_NAME: str = "baseline_single_prompt"


class BaselineAgent(Agent):
    """The one and only agent in the baseline condition.

    Its role prompt asks for a complete SRS in one response, using the
    same section ordering and style rules as the multi-agent conditions
    so downstream evaluation compares like documents.
    """

    role_name = "baseline"
    role_system_prompt = prompts.BASELINE_SYSTEM

    def generate(self, description: str) -> str:
        """Produce the SRS in a single call.

        Args:
            description: The natural-language system description.

        Returns:
            The SRS as Markdown.
        """
        result = self._call(
            phase="initial",
            user_prompt=prompts.baseline_user_prompt(description),
        )
        return result.text


@dataclass
class BaselineResult:
    """Everything produced by one baseline run of one test case.

    Attributes:
        case_id: The test case identifier.
        repetition: Zero-based repetition index.
        srs_markdown: The final assembled SRS document.
    """

    case_id: str
    repetition: int
    srs_markdown: str


def run_baseline(
    description: str,
    *,
    case_id: str,
    repetition: int,
    client: LLMClient,
    settings: Settings,
    logger: ExperimentLogger,
) -> BaselineResult:
    """Run the baseline architecture end-to-end on one test case.

    The SRS the model returns is used verbatim as the "body" of the
    document, with a metadata front matter added so that the file layout
    matches the multi-agent conditions (this is what makes side-by-side
    inspection painless).

    Args:
        description: The natural-language system description.
        case_id: Identifier for the test case.
        repetition: Zero-based repetition index.
        client: The shared LLM client.
        settings: The resolved run configuration.
        logger: The active experiment logger.

    Returns:
        A :class:`BaselineResult`.
    """
    context = RunContext(
        architecture=ARCHITECTURE_NAME,
        case_id=case_id,
        repetition=repetition,
        protocol_block=prompts.ARCHITECTURE_PROTOCOL_BASELINE,
    )
    agent = BaselineAgent(client, context)

    logger.info("[baseline/%s rep=%d] single-prompt generation", case_id, repetition)
    body = agent.generate(description)

    srs = _wrap_with_metadata(
        case_id=case_id,
        repetition=repetition,
        settings=settings,
        description=description,
        body=body,
    )
    return BaselineResult(case_id=case_id, repetition=repetition, srs_markdown=srs)


def _wrap_with_metadata(
    *,
    case_id: str,
    repetition: int,
    settings: Settings,
    description: str,
    body: str,
) -> str:
    """Prepend the standard front matter to the model's raw SRS body.

    Kept separate so the front-matter format matches the multi-agent
    conditions exactly.
    """
    return (
        f"# Software Requirements Specification — {case_id}\n\n"
        "> Generated by the multi-agent SRS generation experiment. "
        "This document is machine-produced and has not been reviewed by a "
        "human requirements engineer.\n\n"
        "## Run metadata\n\n"
        f"- Test case: `{case_id}`\n"
        f"- Repetition index: `{repetition}`\n"
        f"- Architecture: `{ARCHITECTURE_NAME}`\n"
        f"- Run ID: `{settings.run_id}`\n"
        f"- Model: `{settings.model_id}`\n"
        f"- Effort: `{settings.effort}`\n"
        f"- Thinking mode: `{settings.thinking_mode}`\n"
        f"- Revision budget: `0` round(s) (baseline uses a single call)\n"
        f"- Revision rounds executed: `0`\n\n"
        "## Input description\n\n"
        f"> {description.strip().replace(chr(10), chr(10) + '> ')}\n\n"
        f"{body.strip()}\n"
    )
