"""Structured logging for every LLM interaction in the experiment.

The dissertation's central claim is a comparison between agent collaboration
architectures. That claim is only auditable if every model call is recorded in
full, so this module writes two artefacts per run:

``llm_interactions.jsonl``
    One JSON object per line, one line per LLM call (successful or failed).
    This is the primary evidence base: it records the architecture, agent,
    model, exact prompt, exact response, token counts, latency and timestamp,
    which is enough to reconstruct cost, latency and behaviour post hoc.

``run.log``
    A human-readable narrative of the run, for debugging and for including as
    an appendix.

Design decisions worth noting for the reader:

* **Nothing is swallowed.** Failed calls are written to the JSONL file with
  an ``error`` object and re-raised by the caller. A run that degrades must
  do so visibly.
* **Append-only, flushed per record.** If a run crashes half-way, everything
  up to the crash is already on disk.
* **Thread-safe.** Writes are guarded by a lock so that architectures which
  later run agents concurrently do not interleave partial lines.

Note on the module name: this file is ``utils/logging.py`` but, because Python
3 uses absolute imports, ``import logging`` below still resolves to the
standard library module, not to this file.

Typical use::

    with ExperimentLogger.for_run(settings) as logger:
        logger.log_interaction(
            architecture="hierarchical",
            agent="functional_requirements",
            ...
        )
"""

from __future__ import annotations

import json
import logging
import sys
import threading
import time
import uuid
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from types import TracebackType
from typing import Any, Iterator, Mapping, Sequence

# Imported for the convenience constructor and for type hints only; this
# module does not otherwise depend on configuration.
from config.settings import Settings

#: Name of the JSON Lines file holding one record per LLM call.
INTERACTIONS_FILENAME = "llm_interactions.jsonl"

#: Name of the human-readable run log.
RUN_LOG_FILENAME = "run.log"

#: Name of the redacted configuration snapshot written at run start.
CONFIG_SNAPSHOT_FILENAME = "config.json"

_LOG_FORMAT = "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
_LOG_DATEFMT = "%Y-%m-%dT%H:%M:%S%z"


def _utc_now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string with a ``Z`` suffix."""
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace(
        "+00:00", "Z"
    )


# --------------------------------------------------------------------------
# Record types
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class TokenUsage:
    """Token accounting for a single LLM call.

    Attributes:
        input_tokens: Uncached input tokens billed at full rate.
        output_tokens: Tokens generated by the model (including any thinking
            tokens, which are billed as output).
        cache_creation_input_tokens: Input tokens written to the prompt cache.
        cache_read_input_tokens: Input tokens served from the prompt cache.
    """

    input_tokens: int = 0
    output_tokens: int = 0
    cache_creation_input_tokens: int = 0
    cache_read_input_tokens: int = 0

    @property
    def total_input_tokens(self) -> int:
        """Total input tokens processed, cached or not.

        The API reports ``input_tokens`` as the *uncached remainder* only, so
        the true prompt size is the sum of all three input fields.
        """
        return (
            self.input_tokens
            + self.cache_creation_input_tokens
            + self.cache_read_input_tokens
        )

    @property
    def total_tokens(self) -> int:
        """Total tokens processed and generated for this call."""
        return self.total_input_tokens + self.output_tokens

    @classmethod
    def from_response_usage(cls, usage: Any) -> "TokenUsage":
        """Build a :class:`TokenUsage` from an SDK response ``usage`` object.

        Args:
            usage: The ``usage`` attribute of an Anthropic ``Message``. Fields
                absent on the object default to ``0``, so this tolerates SDK
                versions that do not report cache statistics.

        Returns:
            A populated :class:`TokenUsage`.
        """
        return cls(
            input_tokens=int(getattr(usage, "input_tokens", 0) or 0),
            output_tokens=int(getattr(usage, "output_tokens", 0) or 0),
            cache_creation_input_tokens=int(
                getattr(usage, "cache_creation_input_tokens", 0) or 0
            ),
            cache_read_input_tokens=int(
                getattr(usage, "cache_read_input_tokens", 0) or 0
            ),
        )


@dataclass(frozen=True)
class LLMInteraction:
    """A complete record of one call to the language model.

    One of these is written per line to ``llm_interactions.jsonl``. The field
    set is deliberately wide: it is cheaper to record a field now than to
    re-run a paid experiment because a column was missing at analysis time.

    Attributes:
        interaction_id: Unique identifier for this call.
        run_id: Identifier of the run this call belongs to.
        timestamp: UTC ISO-8601 timestamp taken when the call was issued.
        architecture: Condition under test — one of ``hierarchical``,
            ``peer_to_peer``, ``debate``, or ``baseline_single_prompt``.
        agent: Agent role that issued the call (e.g. ``orchestrator``), or
            ``baseline`` for the single-prompt condition.
        case_id: Identifier of the test case being processed.
        repetition: Zero-based repetition index for this (architecture, case)
            pair, used to quantify run-to-run variance.
        phase: Stage within the architecture (e.g. ``initial``, ``review``,
            ``revision``, ``arbitration``), for tracing multi-round protocols.
        model: Model identifier used for this call.
        system_prompt: The system prompt sent, verbatim.
        messages: The ``messages`` array sent, verbatim.
        request_params: Non-prompt request parameters (max_tokens, effort,
            thinking mode), recorded so the exact call can be reconstructed.
        response_text: Concatenated text content of the response.
        stop_reason: Why generation stopped (``end_turn``, ``max_tokens``,
            ``refusal``, ...). Anything other than ``end_turn`` warrants
            scrutiny during analysis.
        usage: Token accounting for the call.
        latency_ms: Wall-clock duration of the call in milliseconds.
        error: Populated only when the call failed; ``None`` otherwise.
    """

    interaction_id: str
    run_id: str
    timestamp: str
    architecture: str
    agent: str
    case_id: str
    repetition: int
    phase: str
    model: str
    system_prompt: str
    messages: Sequence[Mapping[str, Any]]
    request_params: Mapping[str, Any]
    response_text: str
    stop_reason: str | None
    usage: TokenUsage
    latency_ms: float
    error: Mapping[str, Any] | None = None

    def to_json_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable dictionary for the JSONL file."""
        record = asdict(self)
        record["usage"]["total_input_tokens"] = self.usage.total_input_tokens
        record["usage"]["total_tokens"] = self.usage.total_tokens
        return record


@dataclass
class RunTotals:
    """Running aggregates over a run, used for the end-of-run summary.

    Attributes:
        calls: Number of LLM calls issued, including failed ones.
        failed_calls: Number of calls that raised.
        input_tokens: Sum of all input tokens (cached and uncached).
        output_tokens: Sum of all output tokens.
        latency_ms: Sum of per-call wall-clock latency.
    """

    calls: int = 0
    failed_calls: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    latency_ms: float = 0.0

    def add(self, interaction: LLMInteraction) -> None:
        """Accumulate one interaction into the totals."""
        self.calls += 1
        if interaction.error is not None:
            self.failed_calls += 1
        self.input_tokens += interaction.usage.total_input_tokens
        self.output_tokens += interaction.usage.output_tokens
        self.latency_ms += interaction.latency_ms

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable snapshot of the totals."""
        return {
            "calls": self.calls,
            "failed_calls": self.failed_calls,
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "total_tokens": self.input_tokens + self.output_tokens,
            "latency_ms": round(self.latency_ms, 1),
        }


# --------------------------------------------------------------------------
# Logger
# --------------------------------------------------------------------------


class ExperimentLogger:
    """Writes the run log and the LLM interaction log for a single run.

    Use :meth:`for_run` to construct one from a :class:`~config.settings.Settings`
    object, which also creates the run directory and writes the configuration
    snapshot. The logger is a context manager and should be closed so that
    file handles are released and the end-of-run summary is written.

    Args:
        run_dir: Directory to write artefacts into. Created if absent.
        run_id: Identifier stamped onto every interaction record.
        log_level: Verbosity for the console and ``run.log`` handlers.
    """

    def __init__(self, run_dir: Path, run_id: str, log_level: str = "INFO") -> None:
        self.run_dir = run_dir
        self.run_id = run_id
        self.run_dir.mkdir(parents=True, exist_ok=True)

        self.interactions_path = self.run_dir / INTERACTIONS_FILENAME
        self.run_log_path = self.run_dir / RUN_LOG_FILENAME

        self.totals = RunTotals()

        self._lock = threading.Lock()
        self._closed = False
        # Line-buffered append: each record is on disk as soon as it is written,
        # so a crash mid-run still leaves a usable partial log.
        self._interactions_file = self.interactions_path.open(
            "a", encoding="utf-8", buffering=1
        )
        self._logger = self._build_logger(log_level)

        self._logger.info("Run %s started; artefacts in %s", run_id, self.run_dir)

    # -- construction -------------------------------------------------------

    @classmethod
    def for_run(cls, settings: Settings) -> "ExperimentLogger":
        """Create a logger for ``settings`` and snapshot the configuration.

        Creates the run directory, writes the redacted ``config.json``
        provenance record, and returns a ready-to-use logger.

        Args:
            settings: The resolved configuration for this run.

        Returns:
            An open :class:`ExperimentLogger`.
        """
        run_dir = settings.ensure_run_dir()
        logger = cls(run_dir=run_dir, run_id=settings.run_id, log_level=settings.log_level)
        snapshot_path = run_dir / CONFIG_SNAPSHOT_FILENAME
        snapshot_path.write_text(
            json.dumps(settings.to_dict(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        logger.info("Configuration snapshot written to %s", snapshot_path)
        return logger

    def _build_logger(self, log_level: str) -> logging.Logger:
        """Configure a private stdlib logger with file and console handlers.

        A per-run logger name keeps handlers isolated, so constructing a second
        logger (e.g. in a test) does not duplicate the first one's output.
        """
        logger = logging.getLogger(f"experiment.{self.run_id}")
        logger.setLevel(log_level)
        logger.propagate = False
        logger.handlers.clear()

        formatter = logging.Formatter(_LOG_FORMAT, datefmt=_LOG_DATEFMT)

        file_handler = logging.FileHandler(self.run_log_path, encoding="utf-8")
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)

        console_handler = logging.StreamHandler(sys.stderr)
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)

        return logger

    # -- external handlers ---------------------------------------------------

    def add_handler(self, handler: logging.Handler) -> None:
        """Attach an extra handler to the run's narrative logger.

        Lets a caller (e.g. the Streamlit UI) observe the same INFO/WARNING/
        ERROR narrative lines already written to ``run.log`` and the console
        — without this module knowing anything about who's listening. The
        handler receives every record from the moment it is attached, in
        the same thread that issues the LLM calls, so a handler that pushes
        into a UI placeholder sees updates as soon as each call completes.

        Args:
            handler: A configured ``logging.Handler``. Its own formatter (if
                any) is left untouched; a plain default formatter is not
                imposed so the caller controls the display format.
        """
        self._logger.addHandler(handler)

    # -- narrative logging --------------------------------------------------

    def debug(self, message: str, *args: Any) -> None:
        """Log a DEBUG-level message to the run log and console."""
        self._logger.debug(message, *args)

    def info(self, message: str, *args: Any) -> None:
        """Log an INFO-level message to the run log and console."""
        self._logger.info(message, *args)

    def warning(self, message: str, *args: Any) -> None:
        """Log a WARNING-level message to the run log and console."""
        self._logger.warning(message, *args)

    def error(self, message: str, *args: Any, exc_info: bool = False) -> None:
        """Log an ERROR-level message, optionally with a traceback."""
        self._logger.error(message, *args, exc_info=exc_info)

    # -- interaction logging ------------------------------------------------

    def log_interaction(
        self,
        *,
        architecture: str,
        agent: str,
        case_id: str,
        repetition: int,
        phase: str,
        model: str,
        system_prompt: str,
        messages: Sequence[Mapping[str, Any]],
        request_params: Mapping[str, Any],
        response_text: str,
        stop_reason: str | None,
        usage: TokenUsage,
        latency_ms: float,
        error: Mapping[str, Any] | None = None,
    ) -> LLMInteraction:
        """Record one LLM call and append it to ``llm_interactions.jsonl``.

        Args:
            architecture: Condition under test.
            agent: Agent role that issued the call.
            case_id: Test case identifier.
            repetition: Zero-based repetition index.
            phase: Stage within the architecture's protocol.
            model: Model identifier used.
            system_prompt: System prompt sent, verbatim.
            messages: ``messages`` array sent, verbatim.
            request_params: Non-prompt request parameters.
            response_text: Concatenated response text (empty on failure).
            stop_reason: Reported stop reason, if any.
            usage: Token accounting for the call.
            latency_ms: Wall-clock duration in milliseconds.
            error: Error details if the call failed, else ``None``.

        Returns:
            The :class:`LLMInteraction` that was written.

        Raises:
            RuntimeError: If the logger has already been closed.
        """
        interaction = LLMInteraction(
            interaction_id=uuid.uuid4().hex,
            run_id=self.run_id,
            timestamp=_utc_now_iso(),
            architecture=architecture,
            agent=agent,
            case_id=case_id,
            repetition=repetition,
            phase=phase,
            model=model,
            system_prompt=system_prompt,
            messages=list(messages),
            request_params=dict(request_params),
            response_text=response_text,
            stop_reason=stop_reason,
            usage=usage,
            latency_ms=round(latency_ms, 1),
            error=dict(error) if error is not None else None,
        )
        self._write_interaction(interaction)
        return interaction

    def _write_interaction(self, interaction: LLMInteraction) -> None:
        """Serialise one interaction to the JSONL file and update totals."""
        if self._closed:
            raise RuntimeError(
                "ExperimentLogger is closed; cannot record further interactions."
            )

        line = json.dumps(interaction.to_json_dict(), ensure_ascii=False)
        with self._lock:
            self._interactions_file.write(line + "\n")
            self.totals.add(interaction)

        if interaction.error is not None:
            self.error(
                "LLM call FAILED | %s/%s | case=%s rep=%d phase=%s | %s: %s",
                interaction.architecture,
                interaction.agent,
                interaction.case_id,
                interaction.repetition,
                interaction.phase,
                interaction.error.get("type", "UnknownError"),
                interaction.error.get("message", ""),
            )
            return

        if interaction.stop_reason not in (None, "end_turn"):
            # Not fatal, but it means the response may be truncated or refused;
            # surface it rather than letting it pass unnoticed into the results.
            self.warning(
                "Unexpected stop_reason=%r | %s/%s | case=%s rep=%d phase=%s",
                interaction.stop_reason,
                interaction.architecture,
                interaction.agent,
                interaction.case_id,
                interaction.repetition,
                interaction.phase,
            )

        self.info(
            "LLM call | %s/%s | case=%s rep=%d phase=%s | "
            "in=%d out=%d tokens | %.0f ms",
            interaction.architecture,
            interaction.agent,
            interaction.case_id,
            interaction.repetition,
            interaction.phase,
            interaction.usage.total_input_tokens,
            interaction.usage.output_tokens,
            interaction.latency_ms,
        )

    # -- timing helper ------------------------------------------------------

    @staticmethod
    def start_timer() -> float:
        """Return a monotonic start time for use with :meth:`elapsed_ms`."""
        return time.perf_counter()

    @staticmethod
    def elapsed_ms(started_at: float) -> float:
        """Return milliseconds elapsed since ``started_at``."""
        return (time.perf_counter() - started_at) * 1000.0

    # -- reading back -------------------------------------------------------

    def iter_interactions(self) -> Iterator[dict[str, Any]]:
        """Yield every interaction recorded so far, in write order.

        Reads the JSONL file from disk, so it also works for runs logged by a
        previous process (useful for the analysis scripts in later stages).

        Yields:
            One decoded JSON object per recorded interaction.
        """
        if not self.interactions_path.exists():
            return
        with self.interactions_path.open("r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if line:
                    yield json.loads(line)

    # -- lifecycle ----------------------------------------------------------

    def close(self) -> None:
        """Write the end-of-run summary and release file handles.

        Safe to call more than once.
        """
        if self._closed:
            return

        summary = self.totals.to_dict()
        summary_path = self.run_dir / "run_summary.json"
        summary_path.write_text(
            json.dumps({"run_id": self.run_id, **summary}, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        self.info(
            "Run %s finished | %d calls (%d failed) | %d in / %d out tokens | %.1f s",
            self.run_id,
            summary["calls"],
            summary["failed_calls"],
            summary["input_tokens"],
            summary["output_tokens"],
            summary["latency_ms"] / 1000.0,
        )

        with self._lock:
            self._interactions_file.close()
            self._closed = True

        for handler in list(self._logger.handlers):
            handler.close()
            self._logger.removeHandler(handler)

    def __enter__(self) -> "ExperimentLogger":
        """Enter the context manager, returning this logger."""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool:
        """Log any propagating exception, then close. Never suppresses."""
        if exc is not None:
            self.error("Run %s aborted: %s: %s", self.run_id, exc_type.__name__ if exc_type else "?", exc, exc_info=True)
        self.close()
        return False
